### ISSUE TITLE
dxDrawImage: missing color & postGUI argument

### ISSUE THREAD

**Issue by srslyyyy** [IIYAMA12/mta-annotations-for-lua-language-server#1]
![obraz](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/assets/51768772/966f58b2-70d8-480e-8b1c-429cc2cef5ae)

```lua
---@type fun(posX: number, posY: number, width: number, height: number, image: element, rotation?: number, rotationCenterOffsetX?: number, rotationCenterOffsetY?: number): boolean Returns true if successful, false otherwise.```

**Comment by IIYAMA12** [comment]
Fix in: 
https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/commit/fdb506c394583d3c4af738b725d19d591c4617ab
