### ISSUE TITLE
createMarker new argument

### ISSUE THREAD

**Issue by FileEX** [IIYAMA12/mta-annotations-for-lua-language-server#16]
https://wiki.multitheftauto.com/wiki/CreateMarker
![image](https://github.com/user-attachments/assets/ed59d35e-2a79-4c4e-b37e-8321f79caa7c)

**Comment by IIYAMA12** [comment]
Thanks, appreciated!

Added in:
https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/commit/fe8750dd1f1b073646bbed50b12012133cef8333#diff-9ec4ba783d68eb7a429b3465c5f87df4c8ee2c66bc8c0f250e98a0b7f470c05dR493
