### ISSUE TITLE
isPlayerCrosshairVisible & respawnObject

### ISSUE THREAD

**Issue by FileEX** [IIYAMA12/mta-annotations-for-lua-language-server#17]
respawnObject is shared now https://wiki.multitheftauto.com/wiki/RespawnObject

New client function ```isPlayerCrosshairVisible```
https://wiki.multitheftauto.com/wiki/IsPlayerCrosshairVisible

**Comment by IIYAMA12** [comment]
> respawnObject is shared now

Reorganized in: 07fc39533c8b92741599ca4a89caba4ba7c3af15

> New client function isPlayerCrosshairVisible

Added in: bdf796da37486c54ccace7ee7056ce14d11d3f57
