### ISSUE TITLE
New shared function spawnVehicleFlyingComponent

### ISSUE THREAD

**Issue by FileEX** [IIYAMA12/mta-annotations-for-lua-language-server#18]
https://wiki.multitheftauto.com/wiki/SpawnVehicleFlyingComponent

**Comment by IIYAMA12** [comment]
Thx!
Added in: https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/commit/741f9575dd6fe9feb0d232422651d64925f0b95e#diff-9ec4ba783d68eb7a429b3465c5f87df4c8ee2c66bc8c0f250e98a0b7f470c05dR2348
