### ISSUE TITLE
guiSetFont: Missing default-bold-small

### ISSUE THREAD

**Issue by srslyyyy** [IIYAMA12/mta-annotations-for-lua-language-server#2]
![obraz](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/assets/51768772/3198c9ec-7fff-4cb5-8c96-d6d3adf7e73f)

[See GUI fonts](https://wiki.multitheftauto.com/wiki/Standard_GUI_Font_Names)

**Comment by IIYAMA12** [comment]
guiFont type fixed in:
[60c5946](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/commit/60c5946c37b815e314cf10f384636193e157f344)
