### ISSUE TITLE
utf8.len: missing function

### ISSUE THREAD

**Issue by srslyyyy** [IIYAMA12/mta-annotations-for-lua-language-server#3]
![utf8len](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/assets/51768772/d81fcf95-b69e-4d5a-92c6-4a898d2f3320)

**Comment by IIYAMA12** [comment]
Resolved in: [021f07b75bbfd0a590b0529f3b1f920a54fd9a93](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/commit/021f07b75bbfd0a590b0529f3b1f920a54fd9a93)
