### ISSUE TITLE
getPedTotalAmmo: argument 2 is optional

### ISSUE THREAD

**Issue by srslyyyy** [IIYAMA12/mta-annotations-for-lua-language-server#4]
![getPedTotalAmmo](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/assets/51768772/c1bcb81e-a2c6-4c57-9e25-d98df7f5234e)

[2nd argument is optional](https://wiki.multitheftauto.com/wiki/GetPedTotalAmmo)

**Comment by IIYAMA12** [comment]
Resolved in: [021f07b75bbfd0a590b0529f3b1f920a54fd9a93](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/commit/021f07b75bbfd0a590b0529f3b1f920a54fd9a93)
