### ISSUE TITLE
setWorldSpecialPropertyEnabled: new roadsignstext property

### ISSUE THREAD

**Issue by srslyyyy** [IIYAMA12/mta-annotations-for-lua-language-server#6]
![obraz](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/assets/51768772/76156ebb-b33f-40cf-8d2a-87ad56f8cb86)

https://wiki.multitheftauto.com/wiki/SetWorldSpecialPropertyEnabled

**Comment by IIYAMA12** [comment]
Added in c9b2de4
