### ISSUE TITLE
onPlayerPrivateMessage: new content parameter

### ISSUE THREAD

**Issue by srslyyyy** [IIYAMA12/mta-annotations-for-lua-language-server#7]
![obraz](https://github.com/IIYAMA12/mta-annotations-for-lua-language-server/assets/51768772/46eedd39-1e35-4900-be68-108aec6a0137)
https://wiki.multitheftauto.com/wiki/OnPlayerPrivateMessage

**Comment by IIYAMA12** [comment]
Added in c9b2de4
